services:
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./term_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
#------------------------------------------------------------------
  api-gateway:
    container_name: ${API_GATEWAY_CONT}
    build:
      context: ./api-gateway${W}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${API_GATEWAY_PORT}
      - DATA_SERVER_HOST=${DATA_SERVER_CONT}
      - DATA_SERVER_PORT=${DATA_SERVER_PORT}
    networks:
      - backend
#------------------------------------------------------------------
  data-server:
    container_name: ${DATA_SERVER_CONT}
    build:
      context: ./data-server${W}
    ports:
      - "${DATA_SERVER_PORT}:${DATA_SERVER_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${DATA_SERVER_PORT}
    networks:
      - backend
#------------------------------------------------------------------
  matching-key-server:
    depends_on:
      - api-gateway
    container_name: ${MATCHING_KEY_SERVER_CONT}
    build:
      context: ./matching-key-server${W}
    ports:
      - "${MATCHING_KEY_SERVER_PORT}:${MATCHING_KEY_SERVER_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${MATCHING_KEY_SERVER_PORT}
      - CONT_NAME=${MATCHING_KEY_SERVER_CONT}
      - API_GATEWAY_HOST=${API_GATEWAY_CONT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - API_GATEWAY_EVENT_URI=${API_GATEWAY_EVENT_URI}
      - API_GATEWAY_TOPIC_URI=${API_GATEWAY_TOPIC_URI}
    networks:
      - backend
#------------------------------------------------------------------
  matching-server:
    depends_on:
      - api-gateway
    container_name: ${MATCHING_SERVER_CONT}
    build:
      context: ./matching-server${W}
    ports:
      - "${MATCHING_SERVER_PORT}:${MATCHING_SERVER_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${MATCHING_SERVER_PORT}
      - CONT_NAME=${MATCHING_SERVER_CONT}
      - API_GATEWAY_HOST=${API_GATEWAY_CONT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - API_GATEWAY_EVENT_URI=${API_GATEWAY_EVENT_URI}
      - API_GATEWAY_TOPIC_URI=${API_GATEWAY_TOPIC_URI}
    networks:
      - backend
#------------------------------------------------------------------
  pii-detection-server:
    depends_on:
      - ${API_GATEWAY_CONT}
      - mysql
    container_name: ${PII_DETECTION_SERVER_CONT}
    build:
      context: ./pii-detection-server${W}
    ports:
      - "${PII_DETECTION_SERVER_PORT}:${PII_DETECTION_SERVER_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PII_DETECTION_SERVER_PORT}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - THRESHOLD=
      - CONT_NAME=${PII_DETECTION_SERVER_CONT}
      - API_GATEWAY_HOST=${API_GATEWAY_CONT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - API_GATEWAY_EVENT_URI=${API_GATEWAY_EVENT_URI}
      - API_GATEWAY_TOPIC_URI=${API_GATEWAY_TOPIC_URI}
    networks:
      - backend
#------------------------------------------------------------------
  pseudonymization-server:
    depends_on:
      - api-gateway
    container_name: ${PSEUDONYMIZATION_SERVER_CONT}
    build:
      context: ./pseudonymization-server${W}
    ports:
      - "${PSEUDONYMIZATION_SERVER_PORT}:${PSEUDONYMIZATION_SERVER_PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PSEUDONYMIZATION_SERVER_PORT}
      - CONT_NAME=${PSEUDONYMIZATION_SERVER_CONT}
      - API_GATEWAY_HOST=${API_GATEWAY_CONT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - API_GATEWAY_EVENT_URI=${API_GATEWAY_EVENT_URI}
      - API_GATEWAY_TOPIC_URI=${API_GATEWAY_TOPIC_URI}
    networks:
      - backend

      
networks:
  backend:
    driver: bridge
