class MessageOption:
    MESSAGE_TYPE = "message_type"
    CLIENT_ID = "client_id"
    TOPIC_NAME = "topic_name"
    PARTITION = "partition"
    PAYLOAD = "payload"
    OFFSET = "offset"
    COUNT = "count"
    REQUEST_ID = "request_id"
    OK = "ok"